### ISSUE TITLE
ex02

### ISSUE THREAD

**Issue by atchoglogilbert** [AchelDrinker/CPP-Module-09#1]
Hey! This is not really an issue. Could you tell me why you used the function sort with no extra implementations in ex02? I mean, the subject says we are supposed to use a merge-sort algorithm and std::sort uses the introsort which implements the insertion sort but no merge sort whatsoever, or am I mistaken? I'd really appreciate an answer and to learn from you! Good luck on your projects!

**Comment by AchelDrinker** [comment]
Hi,
Thank you for this report. In fact, my algorithm isn't finished. I have pushed this project to get the correction file and work on it. You have some things which differ between the subject and the correction and the correction isn't totally correct. Normally, I will finish the project today and repush.

**Comment by atchoglogilbert** [comment]
Hey! Thanks for the reply! Yes, I noticed on the evaluation sheet it asked to check for some things which were not mentioned in the subject:

- in ex00, using the nearest lowest value if no corresponding date was found
- in ex01, passing operations with values >= 10 to the program, which is why the third test fails;

I hope, your evaluators did not fail you because of this disinformation.

It would really be nice to learn how you implemented the merge-sort with the containers. All the best!

**Comment by AchelDrinker** [comment]
The correction is false.
If you do the maths, you havent 42 for result in the third one. You have to do this :
1 2 * 2 / 5 + 4 6 * 6 / 8 * 2 / + 2 * 2 -

Take care to handle the "/ +" part of this

To implement merge sort in vector and list, you got some example on Google.
